// GENERATED CODE - DO NOT MODIFY BY HAND
// This file will be generated by build_runner
// Run: flutter pub run build_runner build

part of 'note_model.dart';

NoteModel _$NoteModelFromJson(Map<String, dynamic> json) => NoteModel(
      id: json['id'] as int?,
      userId: json['user_id'] as int?,
      content: json['content'] as String,
      embedding: (json['embedding'] as List<dynamic>?)
          ?.map((e) => (e as num).toDouble())
          .toList(),
      embeddingModel: json['embedding_model'] as String?,
      tags: json['tags'] as String?,
      createdAt: json['created_at'] as String?,
      updatedAt: json['updated_at'] as String?,
      delFlag: json['del_flag'] as String?,
    );

Map<String, dynamic> _$NoteModelToJson(NoteModel instance) {
  final val = <String, dynamic>{};

  void writeNotNull(String key, dynamic value) {
    if (value != null) {
      val[key] = value;
    }
  }

  writeNotNull('id', instance.id);
  writeNotNull('user_id', instance.userId);
  val['content'] = instance.content;
  writeNotNull('embedding', instance.embedding);
  writeNotNull('embedding_model', instance.embeddingModel);
  writeNotNull('tags', instance.tags);
  writeNotNull('created_at', instance.createdAt);
  writeNotNull('updated_at', instance.updatedAt);
  writeNotNull('del_flag', instance.delFlag);
  return val;
}
