// GENERATED CODE - DO NOT MODIFY BY HAND
// This file will be generated by build_runner
// Run: flutter pub run build_runner build

part of 'rag_response_model.dart';

RAGResponseModel _$RAGResponseModelFromJson(Map<String, dynamic> json) =>
    RAGResponseModel(
      answer: json['answer'] as String?,
      question: json['question'] as String,
      relatedNotes: (json['related_notes'] as List<dynamic>?)
          ?.map((e) => NoteModel.fromJson(e as Map<String, dynamic>))
          .toList(),
      success: json['success'] as bool,
      errorMessage: json['error_message'] as String?,
      processingTime: json['processing_time'] as int?,
      similarityThreshold: (json['similarity_threshold'] as num?)?.toDouble(),
      maxResults: json['max_results'] as int?,
    );

Map<String, dynamic> _$RAGResponseModelToJson(RAGResponseModel instance) {
  final val = <String, dynamic>{};

  void writeNotNull(String key, dynamic value) {
    if (value != null) {
      val[key] = value;
    }
  }

  writeNotNull('answer', instance.answer);
  val['question'] = instance.question;
  writeNotNull('related_notes',
      instance.relatedNotes?.map((e) => e.toJson()).toList());
  val['success'] = instance.success;
  writeNotNull('error_message', instance.errorMessage);
  writeNotNull('processing_time', instance.processingTime);
  writeNotNull('similarity_threshold', instance.similarityThreshold);
  writeNotNull('max_results', instance.maxResults);
  return val;
}
