// GENERATED CODE - DO NOT MODIFY BY HAND
// This file will be generated by build_runner
// Run: flutter pub run build_runner build

part of 'review_record_model.dart';

ReviewRecordModel _$ReviewRecordModelFromJson(Map<String, dynamic> json) =>
    ReviewRecordModel(
      id: json['id'] as int?,
      noteId: json['note_id'] as int,
      userId: json['user_id'] as int?,
      quality: json['quality'] as int,
      easinessFactor: (json['easiness_factor'] as num?)?.toDouble(),
      intervalDays: json['interval_days'] as int?,
      repetitions: json['repetitions'] as int?,
      nextReviewDate: json['next_review_date'] as String,
      reviewedAt: json['reviewed_at'] as String?,
    );

Map<String, dynamic> _$ReviewRecordModelToJson(ReviewRecordModel instance) {
  final val = <String, dynamic>{};

  void writeNotNull(String key, dynamic value) {
    if (value != null) {
      val[key] = value;
    }
  }

  writeNotNull('id', instance.id);
  val['note_id'] = instance.noteId;
  writeNotNull('user_id', instance.userId);
  val['quality'] = instance.quality;
  writeNotNull('easiness_factor', instance.easinessFactor);
  writeNotNull('interval_days', instance.intervalDays);
  writeNotNull('repetitions', instance.repetitions);
  val['next_review_date'] = instance.nextReviewDate;
  writeNotNull('reviewed_at', instance.reviewedAt);
  return val;
}
